# Generated by Django 4.2.11 on 2024-03-20 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notes',
            name='links',
            field=models.URLField(null=True),
        ),
        migrations.DeleteModel(
            name='YoutubeLinks',
        ),
    ]
