# Generated by Django 4.2.11 on 2024-03-22 07:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_notes_links_delete_youtubelinks'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='documents',
            name='upload_documents',
        ),
    ]
