# Generated by Django 4.2.11 on 2024-03-22 07:41

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_documents_upload_documents'),
    ]

    operations = [
        migrations.AddField(
            model_name='documents',
            name='upload_documents',
            field=models.FileField(null=True, upload_to=core.models.user_directory_path),
        ),
    ]
