# Generated by Django 4.2.11 on 2024-03-23 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_documents_upload_documents'),
    ]

    operations = [
        migrations.AddField(
            model_name='documents',
            name='documents_file',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
