# Generated by Django 4.2.11 on 2024-03-23 17:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_documents_documents_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='documents',
            name='documents_file',
        ),
    ]
