# Generated by Django 4.2.11 on 2024-03-24 05:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_remove_documents_documents_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documents',
            name='notes',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='note_id', to='core.notes'),
        ),
    ]
