# Generated by Django 4.2.11 on 2024-04-04 12:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_documents_notes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notes',
            name='documents',
        ),
        migrations.DeleteModel(
            name='Documents',
        ),
    ]
